# Site settings
title: Minimal Staticman v3 Demo
subtitle: A barebone GitHub Pages with static comments
email: your-email@domain.com
description: Test
baseurl: ""
url: "https://kiwichat.github.io/TestStaticmanLab/"
locale: en
github_username:  KiwiChat

# Build settings
markdown: kramdown

staticman:
  api: "https://staticman.ml/v3/entry/github/vincenttam/TestStaticmanLab/master/comments"
  path: "_data/comments/test-slug"
